# Generated by Django 5.0.6 on 2026-10-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetrics',
            name='publish_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='publishing.publishjob'),
        ),
        migrations.AddField(
            model_name='postmetricsnapshot',
            name='post_metrics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.postmetrics'),
        ),
        migrations.AddIndex(
            model_name='accountmetricsnapshot',
            index=models.Index(fields=['company', 'date'], name='analytics_a_company_977f33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountmetricsnapshot',
            unique_together={('social_account', 'date')},
        ),
        migrations.AddIndex(
            model_name='postmetrics',
            index=models.Index(fields=['company', 'published_at'], name='analytics_p_company_9917db_idx'),
        ),
        migrations.AddIndex(
            model_name='postmetrics',
            index=models.Index(fields=['company', 'platform'], name='analytics_p_company_dedd37_idx'),
        ),
    ]
