# Generated by Django 5.0.6 on 2026-08-21 12:15

import apps.video_generation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('content_calendar', '0002_contentcalendaritem_source_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_type', models.CharField(choices=[('instagram_reel', 'Instagram Reel'), ('facebook_reel', 'Facebook Reel'), ('linkedin_video', 'LinkedIn Video'), ('short_video', 'Short Video'), ('promotional_video', 'Promotional Video'), ('product_video', 'Product Video'), ('educational_video', 'Educational Video')], max_length=30)),
                ('aspect_ratio', models.CharField(choices=[('9:16', 'Vertical (9:16)'), ('1:1', 'Square (1:1)'), ('16:9', 'Landscape (16:9)')], default='9:16', max_length=10)),
                ('target_duration_seconds', models.PositiveIntegerField(default=30)),
                ('prompt_brief', models.TextField(blank=True, help_text='What the video should be about.')),
                ('product_info', models.TextField(blank=True, help_text='Product information to ground the script.')),
                ('voice_over_enabled', models.BooleanField(default=True)),
                ('subtitles_enabled', models.BooleanField(default=True)),
                ('include_logo', models.BooleanField(default=True)),
                ('music_enabled', models.BooleanField(default=False, help_text='Background music mixing has no configured provider yet - left off by default.')),
                ('script', models.TextField(blank=True, help_text='Full narration script, assembled from all scenes.')),
                ('subtitles_srt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('rendering', 'Rendering'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.video_generation.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.video_generation.models.video_upload_path)),
                ('resolution', models.CharField(blank=True, help_text='e.g. "1080x1920".', max_length=20)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_generation_requests', to='companies.company')),
                ('content_calendar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_generation_requests', to='content_calendar.contentcalendaritem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene_number', models.PositiveSmallIntegerField()),
                ('narration', models.TextField(blank=True, help_text='The voice-over line for this scene.')),
                ('visual_description', models.TextField(blank=True, help_text='What should be shown on screen.')),
                ('duration_seconds', models.FloatField(default=4.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.video_generation.models.scene_image_upload_path)),
                ('voice_over_audio', models.FileField(blank=True, null=True, upload_to=apps.video_generation.models.scene_audio_upload_path)),
                ('video_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='video_generation.videogenerationrequest')),
            ],
            options={
                'ordering': ['scene_number'],
                'unique_together': {('video_request', 'scene_number')},
            },
        ),
    ]
