# Generated by Django 5.0.6 on 2026-08-26 12:48

import apps.video_generation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationrequest',
            name='ai_motion_enabled',
            field=models.BooleanField(default=True, help_text='Animate each scene image into a short AI-generated video clip instead of a static zoom/pan. Falls back to zoom/pan automatically if no video provider is configured (REPLICATE_API_TOKEN unset).'),
        ),
        migrations.AddField(
            model_name='videoscene',
            name='video_clip',
            field=models.FileField(blank=True, help_text='AI-animated version of `image`, if AI motion was enabled and available.', null=True, upload_to=apps.video_generation.models.scene_video_clip_upload_path),
        ),
    ]
