# Generated by Django 5.0.6 on 2026-10-01 21:50

import apps.video_generation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generation', '0002_videogenerationrequest_ai_motion_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videogenerationrequest',
            name='include_outro',
            field=models.BooleanField(default=True, help_text='Append a short brand-coloured end card with the logo, company name and CTA/website.'),
        ),
        migrations.AlterField(
            model_name='videogenerationrequest',
            name='music_enabled',
            field=models.BooleanField(default=False, help_text='Mix a background music track (from the admin-managed music library) under the voice-over.'),
        ),
        migrations.CreateModel(
            name='BackgroundMusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=apps.video_generation.models.music_upload_path)),
                ('mood', models.CharField(choices=[('upbeat', 'Upbeat'), ('calm', 'Calm'), ('corporate', 'Corporate'), ('cinematic', 'Cinematic'), ('inspirational', 'Inspirational'), ('festive', 'Festive'), ('other', 'Other')], default='other', max_length=15)),
                ('license_note', models.CharField(blank=True, help_text='Where it came from / license terms.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='videogenerationrequest',
            name='music_track',
            field=models.ForeignKey(blank=True, help_text='Specific track to use; blank = a random active track from the library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='video_generation.backgroundmusictrack'),
        ),
    ]
