# Generated by Django 5.0.6 on 2026-10-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        ('content_calendar', '0005_contentreviewevent'),
        ('social_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=15)),
                ('post_type', models.CharField(choices=[('image', 'Image post'), ('carousel', 'Carousel'), ('video', 'Video'), ('reel', 'Reel'), ('story', 'Story'), ('text', 'Text only')], default='image', max_length=10)),
                ('caption', models.TextField(blank=True)),
                ('media', models.JSONField(blank=True, default=list, help_text='Snapshot of media to post: [{"kind": "image"|"video", "source": ..., "id": ..., "name": ...}].')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('queued', 'Queued'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='[{"at": iso, "attempt": n, "message": ...}]')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_jobs', to='companies.company')),
                ('content_calendar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_jobs', to='content_calendar.contentcalendaritem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_jobs', to='social_accounts.socialaccount')),
            ],
            options={
                'ordering': ['-scheduled_at', '-id'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='publishing__status_8845ad_idx'), models.Index(fields=['company', 'status'], name='publishing__company_290347_idx'), models.Index(fields=['company', '-published_at'], name='publishing__company_1881c0_idx')],
            },
        ),
    ]
