# Generated by Django 5.0.6 on 2026-08-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('content_generated', 'Content Generated'), ('approval_required', 'Approval Required'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('content_regenerated', 'Content Regenerated'), ('content_published', 'Content Published'), ('publishing_failed', 'Publishing Failed'), ('reminder', 'Reminder'), ('company_created', 'Company Created'), ('client_added', 'Client Added')], max_length=30),
        ),
    ]
