# Generated by Django 5.0.6 on 2026-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('content_generated', 'Content Generated'), ('approval_required', 'Approval Required'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('content_regenerated', 'Content Regenerated'), ('content_published', 'Content Published'), ('publishing_failed', 'Publishing Failed'), ('reminder', 'Reminder'), ('company_created', 'Company Created'), ('client_added', 'Client Added'), ('admin_added', 'Admin Added'), ('social_token_expired', 'Social Token Expired'), ('suspicious_login', 'Suspicious Login Activity'), ('post_scheduled', 'Post Scheduled'), ('report_ready', 'Report Ready'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('usage_limit_reached', 'Usage Limit Reached'), ('analytics_sync_failed', 'Analytics Sync Failed')], max_length=30),
        ),
    ]
