# Generated by Django 5.0.6 on 2026-08-19 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_analysis', models.TextField(blank=True)),
                ('brand_guidelines_analysis', models.TextField(blank=True)),
                ('products_services_analysis', models.TextField(blank=True)),
                ('audience_analysis', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='Synthesized brand context used to ground later AI generations.')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_context', to='companies.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Context',
                'verbose_name_plural': 'Brand Contexts',
            },
        ),
        migrations.CreateModel(
            name='StrategyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('content_ideas', 'Content Ideas'), ('topic_suggestions', 'Topic Suggestions'), ('content_themes', 'Content Themes'), ('campaign_suggestions', 'Campaign Suggestions'), ('posting_suggestions', 'Posting Suggestions'), ('content_strategy', 'Content Strategy'), ('platform_strategy', 'Platform Strategy'), ('audience_strategy', 'Audience Strategy'), ('campaign_strategy', 'Campaign Strategy')], max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Optional extra guidance the admin supplied for this generation.')),
                ('result', models.JSONField(default=dict, help_text='Structured output; shape depends on kind.')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_outputs', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
