# Generated by Django 5.0.6 on 2026-10-01 21:50

import apps.whatsapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('business_number', models.CharField(blank=True, help_text='The WhatsApp Business number messages come from (display only).', max_length=20)),
                ('client_numbers', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "phone": "+91..."}]')),
                ('internal_numbers', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "phone": "+91..."}]')),
                ('include_client_users', models.BooleanField(default=True, help_text="Also message the company's client logins who turned on WhatsApp notifications in their settings.")),
                ('group_name', models.CharField(blank=True, max_length=120)),
                ('group_description', models.TextField(blank=True)),
                ('group_status', models.CharField(choices=[('not_created', 'Not created'), ('active', 'Active'), ('inactive', 'Inactive')], default='not_created', max_length=15)),
                ('group_invite_link', models.URLField(blank=True, help_text='Optional link to a WhatsApp group created in the app for human conversation.')),
                ('group_created_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_events', models.JSONField(blank=True, default=apps.whatsapp.models._all_events)),
                ('language_code', models.CharField(default='en', help_text='Template language, e.g. en, en_US, hi.', max_length=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='companies.company')),
            ],
            options={
                'verbose_name': 'WhatsApp configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('approval_required', 'Content generated - approval required'), ('content_regenerated', 'Content regenerated'), ('content_approved', 'Content approved'), ('content_rejected', 'Content rejected'), ('content_published', 'Content published'), ('publishing_failed', 'Publishing failed'), ('approval_reminder', 'Approval reminder'), ('monthly_report', 'Monthly report ready')], max_length=30)),
                ('name', models.CharField(help_text='Template name exactly as created in WhatsApp Manager.', max_length=512)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('marketing', 'Marketing')], default='utility', max_length=15)),
                ('body', models.TextField(help_text='Body text as submitted to Meta, with {{1}}, {{2}} ... placeholders.')),
                ('variables', models.JSONField(default=list, help_text='Ordered context keys for {{1}}, {{2}}, ...')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_status', models.CharField(choices=[('unknown', 'Not synced'), ('approved', 'Approved'), ('pending', 'Pending review'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('missing', 'Not found in WhatsApp Manager')], default='unknown', max_length=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['event', 'language_code'],
                'unique_together': {('event', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=30)),
                ('to_number', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_type', models.CharField(blank=True, help_text='client / internal / user / test', max_length=10)),
                ('template_name', models.CharField(blank=True, max_length=512)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('body', models.TextField(blank=True, help_text='Rendered preview of what was sent.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=10)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='whatsapp_wh_company_932adf_idx')],
            },
        ),
    ]
