# Generated by Django 5.0.6 on 2026-09-23 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_notification_emails', models.BooleanField(default=True, help_text='Mirror in-app notifications as emails (Epic 13).')),
                ('default_variation_count', models.PositiveSmallIntegerField(default=3, help_text='Default number of AI variations for a new generation request (1-3).')),
                ('max_variation_count', models.PositiveSmallIntegerField(default=3, help_text='Hard ceiling on variations an admin can request at once (1-3).')),
                ('daily_generation_limit_per_company', models.PositiveIntegerField(default=0, help_text='Max combined creative + video generation requests a company can start per day. 0 = unlimited.')),
                ('max_upload_size_mb', models.PositiveIntegerField(default=10, help_text='Max file size for brand asset uploads, in MB.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
