# Generated by Django 5.0.6 on 2026-09-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='send_notification_emails',
            field=models.BooleanField(default=False, help_text='Mirror in-app notifications as emails (Epic 13).'),
        ),
    ]
