# Generated by Django 5.0.6 on 2026-10-01 21:50

import apps.platform_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_settings', '0002_alter_platformsettings_send_notification_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='ai_image_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ai_image_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ai_text_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ai_text_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ai_video_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ai_video_provider',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='analytics_sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='analytics_sync_interval_hours',
            field=models.PositiveSmallIntegerField(default=6, help_text='How often published-post metrics are refreshed from the platforms (1-48).'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='approval_reminder_hours',
            field=models.PositiveIntegerField(default=24, help_text='Remind clients about content still pending their approval after this many hours. 0 = off.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='auto_schedule_on_approval',
            field=models.BooleanField(default=False, help_text='When content is approved, automatically schedule it to every connected account for its platforms at the calendar item date/time (Epic 22: Publishing automation).'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='content_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('bn', 'Bengali'), ('ml', 'Malayalam'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic')], default='en', help_text='Language AI-generated captions, scripts and voice-overs are written in.', max_length=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_publish_time',
            field=models.TimeField(default=apps.platform_settings.models._default_publish_time, help_text='Publish time used when a calendar item has a date but no time.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_timezone',
            field=models.CharField(blank=True, help_text='IANA timezone (e.g. Asia/Kolkata) used to interpret calendar dates/times when scheduling posts. Blank = the server TIME_ZONE.', max_length=64),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_reports_to_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='enforce_subscription_limits',
            field=models.BooleanField(default=False, help_text='Block generation/publishing once a company exceeds its plan limits or has no active subscription. Off = usage is tracked and shown, but never blocks work.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='monthly_reports_enabled',
            field=models.BooleanField(default=True, help_text="Generate every active company's monthly report automatically."),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='publish_max_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many times a failed publish is attempted before it is marked failed (1-10).'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='publishing_enabled',
            field=models.BooleanField(default=True, help_text='Global kill switch - when off, scheduled posts wait instead of publishing.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='report_day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text="Day of the month (1-28) the previous month's reports are generated."),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='subscription_expiry_reminder_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Notify admins this many days before a subscription expires.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='whatsapp_reports_to_clients',
            field=models.BooleanField(default=True),
        ),
    ]
