"""Regenerates docs/database.md and docs/api.md from the code (Epic 28: API documentation,
Database documentation) so the reference never drifts from the real models and routes.

    python manage.py generate_reference_docs
"""

import inspect
from pathlib import Path

from django.apps import apps
from django.conf import settings
from django.core.management.base import BaseCommand
from django.db import models
from django.urls import URLPattern, URLResolver, get_resolver

DOCS_DIR = Path(settings.BASE_DIR).parent / 'docs'
METHODS = ('get', 'post', 'put', 'patch', 'delete')


def _first_paragraph(text):
    if not text:
        return ''
    cleaned = inspect.cleandoc(text)
    return ' '.join(cleaned.split('\n\n')[0].split())


def _field_type(field):
    if isinstance(field, models.ForeignKey):
        return f'FK → {field.related_model._meta.label}'
    if isinstance(field, models.OneToOneField):
        return f'1:1 → {field.related_model._meta.label}'
    if isinstance(field, models.ManyToManyField):
        return f'M2M → {field.related_model._meta.label}'
    kind = field.get_internal_type()
    if getattr(field, 'max_length', None) and kind in ('CharField', 'SlugField', 'URLField', 'EmailField'):
        kind += f'({field.max_length})'
    if getattr(field, 'choices', None):
        kind += ' · choices'
    return kind


def _escape(text):
    return str(text).replace('|', '\\|').replace('\n', ' ')


class Command(BaseCommand):
    help = 'Regenerate docs/database.md and docs/api.md from models and URL patterns.'

    def handle(self, *args, **options):
        DOCS_DIR.mkdir(exist_ok=True)
        (DOCS_DIR / 'database.md').write_text(self.database_doc(), encoding='utf-8')
        (DOCS_DIR / 'api.md').write_text(self.api_doc(), encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(f'Wrote {DOCS_DIR / "database.md"} and {DOCS_DIR / "api.md"}'))

    # ------------------------------------------------------------ database
    def database_doc(self):
        lines = [
            '# Database reference',
            '',
            '> Generated by `python manage.py generate_reference_docs` - edit the models, not this file.',
            '',
            'PostgreSQL in every environment (SQLite works for quick local experiments). Every tenant-owned',
            'table carries a `company` foreign key - that column is what enforces company data isolation',
            '(Epic 25). Media files are stored outside the database (local disk or S3/R2); tables only hold',
            'their paths.',
            '',
        ]
        local_apps = [config for config in apps.get_app_configs() if config.name.startswith('apps.')]
        lines.append('## Contents')
        lines.append('')
        for config in local_apps:
            lines.append(f'- [{config.verbose_name}](#{config.label}) - ' + ', '.join(m.__name__ for m in config.get_models()))
        lines.append('')
        for config in local_apps:
            lines += [f'<a id="{config.label}"></a>', f'## {config.verbose_name} (`{config.name}`)', '']
            for model in config.get_models():
                meta = model._meta
                lines += [f'### {model.__name__}', '', f'Table `{meta.db_table}`.']
                doc = _first_paragraph(model.__doc__)
                if doc and not doc.startswith(model.__name__ + '('):
                    lines += ['', doc]
                lines += ['', '| Field | Type | Null | Notes |', '|---|---|---|---|']
                for field in meta.get_fields():
                    if field.auto_created and not field.concrete:
                        continue
                    if not getattr(field, 'concrete', False) and not isinstance(field, models.ManyToManyField):
                        continue
                    notes = _escape(getattr(field, 'help_text', '') or '')
                    if getattr(field, 'primary_key', False):
                        notes = 'Primary key' + (f'. {notes}' if notes else '')
                    if getattr(field, 'unique', False) and not getattr(field, 'primary_key', False):
                        notes = ('Unique. ' + notes).strip()
                    null = 'yes' if getattr(field, 'null', False) else ''
                    lines.append(f'| `{field.name}` | {_field_type(field)} | {null} | {notes} |')
                if meta.unique_together:
                    lines += ['', f'Unique together: {", ".join("(" + ", ".join(group) + ")" for group in meta.unique_together)}']
                lines.append('')
        return '\n'.join(lines) + '\n'

    # ------------------------------------------------------------ api
    def _walk(self, patterns, prefix=''):
        for entry in patterns:
            if isinstance(entry, URLResolver):
                yield from self._walk(entry.url_patterns, prefix + str(entry.pattern))
            elif isinstance(entry, URLPattern):
                yield prefix + str(entry.pattern), entry

    def api_doc(self):
        lines = [
            '# API reference',
            '',
            '> Generated by `python manage.py generate_reference_docs`. The interactive, always-current version',
            '> with request/response schemas is served by the backend at **`/api/docs/`** (Swagger UI) and',
            '> **`/api/redoc/`**; the raw OpenAPI schema is at `/api/schema/`.',
            '',
            '## Conventions',
            '',
            '- Base path `/api/v1/`. JSON in and out (file uploads use multipart/form-data).',
            '- Auth: `POST /api/v1/auth/login/` returns `access` + `refresh` JWTs. Send',
            '  `Authorization: Bearer <access>` on every request; refresh with `POST /api/v1/auth/refresh/`.',
            '- Roles: **Admin** (internal team) and **Client** (business user). Company-scoped endpoints',
            '  (`/companies/<id>/...`) 404 for a client who is not a member of that company, or who has not',
            '  been granted that page on the Access Control screen.',
            '- Lists are paginated: `?page=N`, response `{count, next, previous, results}` (20 per page).',
            '- Errors: `{"detail": "..."}` or `{"field": ["message"]}` with the matching HTTP status.',
            '',
        ]
        rows = {}
        for path, pattern in self._walk(get_resolver().url_patterns):
            if not path.startswith('api/v1/'):
                continue
            view = getattr(pattern.callback, 'view_class', None) or getattr(pattern.callback, 'cls', None)
            if view is None:
                continue
            methods = [m.upper() for m in METHODS if hasattr(view, m)]
            if hasattr(view, 'get_queryset') and 'GET' not in methods and hasattr(view, 'list'):
                methods.insert(0, 'GET')
            permissions = ', '.join(p.__name__ for p in getattr(view, 'permission_classes', []) or []) or 'Authenticated'
            clean = '/' + path.replace('<int:', '{').replace('<str:', '{').replace('<uuid:', '{').replace('>', '}')
            group = clean.split('/')[3] if len(clean.split('/')) > 3 else 'root'
            if group == 'companies' and clean.count('/') > 4 and '{company_id}' in clean:
                group = 'companies/' + clean.split('/')[5]
            rows.setdefault(group, []).append((clean, ', '.join(methods), permissions, _first_paragraph(view.__doc__)))

        for group in sorted(rows):
            lines += [f'## `{group}`', '', '| Path | Methods | Permission | Description |', '|---|---|---|---|']
            for clean, methods, permissions, doc in rows[group]:
                lines.append(f'| `{clean}` | {methods} | {permissions} | {_escape(doc)} |')
            lines.append('')
        return '\n'.join(lines) + '\n'
