# Generated by Django 5.0.6 on 2026-08-27 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=15)),
                ('account_name', models.CharField(help_text='Admin-facing label, e.g. "Acme Restaurant IG".', max_length=255)),
                ('account_id', models.CharField(blank=True, help_text='External page / organization / business account ID.', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Encrypted at rest - never exposed via the API.')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('disconnected', 'Disconnected')], default='connected', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='companies.company')),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
