# Generated by Django 5.0.6 on 2026-10-01 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        ('social_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='connection_method',
            field=models.CharField(choices=[('oauth', 'OAuth'), ('manual', 'Manual token')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='last_error',
            field=models.TextField(blank=True, help_text='Most recent connection/publishing error, if any.'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Platform extras: page_id, username, picture_url, followers_count, urn, account_type.'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Encrypted at rest (LinkedIn programmatic refresh).'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='refresh_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='Permissions granted to the token.'),
        ),
        migrations.CreateModel(
            name='SocialOAuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('meta', 'Meta (Facebook & Instagram)'), ('linkedin', 'LinkedIn')], max_length=10)),
                ('payload', models.TextField(help_text='Encrypted JSON list of discovered candidate accounts (with tokens).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_oauth_sessions', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
