# Generated by Django 5.0.6 on 2026-09-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('auth', 'Authentication'), ('company', 'Company'), ('client', 'Client'), ('calendar', 'Content Calendar'), ('creative', 'Creative Generation'), ('video', 'Video Generation'), ('approval', 'Content Approval'), ('social', 'Social Accounts'), ('settings', 'Settings')], max_length=20)),
                ('action', models.CharField(help_text='Short verb phrase, e.g. "Company updated".', max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null for actions not tied to a specific company (e.g. admin login).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, help_text='Null for system-triggered actions (e.g. scheduled auto-generation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', '-created_at'], name='activity_lo_module_8a62c6_idx'), models.Index(fields=['company', '-created_at'], name='activity_lo_company_252e94_idx')],
            },
        ),
    ]
