# Generated by Django 5.0.6 on 2026-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('auth', 'Authentication'), ('company', 'Company'), ('client', 'Client'), ('calendar', 'Content Calendar'), ('creative', 'Creative Generation'), ('video', 'Video Generation'), ('approval', 'Content Approval'), ('social', 'Social Accounts'), ('settings', 'Settings'), ('publishing', 'Publishing'), ('whatsapp', 'WhatsApp'), ('analytics', 'Analytics'), ('reports', 'Reports'), ('subscription', 'Subscription')], max_length=20),
        ),
    ]
