# Generated by Django 5.0.6 on 2026-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_avatar_user_email_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
