# Generated by Django 5.0.6 on 2026-10-01 21:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=15)),
                ('creative_limit', models.PositiveIntegerField(default=0, help_text='Creative generations per month. 0 = unlimited.')),
                ('video_limit', models.PositiveIntegerField(default=0, help_text='Video generations per month. 0 = unlimited.')),
                ('publishing_limit', models.PositiveIntegerField(default=0, help_text='Published posts per month. 0 = unlimited.')),
                ('storage_limit_mb', models.PositiveIntegerField(default=0, help_text='Total media storage. 0 = unlimited.')),
                ('social_account_limit', models.PositiveIntegerField(default=0, help_text='Connected social accounts. 0 = unlimited.')),
                ('allowed_platforms', models.JSONField(blank=True, default=list, help_text='Platforms this plan may connect/publish to. Empty = all.')),
                ('features', models.JSONField(blank=True, default=list, help_text='Marketing feature bullets shown for the plan.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Payment overdue'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Expiry date. Blank = open-ended.', null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Reminder only - renewal is still recorded manually.')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creative_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('video_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('publishing_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_limit_mb_override', models.PositiveIntegerField(blank=True, null=True)),
                ('social_account_limit_override', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_reminder_sent_on', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=60)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_paid', 'Partially paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded'), ('void', 'Void')], default='pending', max_length=15)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank transfer'), ('upi', 'UPI'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], max_length=15)),
                ('payment_reference', models.CharField(blank=True, help_text='UTR / cheque no. / transaction ID.', max_length=120)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='billing/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_bytes', models.PositiveBigIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshot', to='companies.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'status'], name='subscriptio_company_c201ce_idx'),
        ),
    ]
