# Generated by Django 5.0.6 on 2026-08-21 07:17

import apps.creative_generation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('content_calendar', '0002_contentcalendaritem_source_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creative_type', models.CharField(choices=[('instagram_post', 'Instagram Post'), ('facebook_post', 'Facebook Post'), ('linkedin_post', 'LinkedIn Post'), ('carousel', 'Carousel'), ('story', 'Story'), ('promotional_creative', 'Promotional Creative'), ('festival_creative', 'Festival Creative'), ('product_creative', 'Product Creative')], max_length=30)),
                ('prompt_brief', models.TextField(blank=True, help_text='Visual brief / instructions for this generation.')),
                ('product_info', models.TextField(blank=True, help_text='Product information to ground the generation.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('usage', models.JSONField(blank=True, default=dict, help_text='Provider usage metadata (e.g. image/token counts).')),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='companies.company')),
                ('content_calendar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to='content_calendar.contentcalendaritem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation_number', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to=apps.creative_generation.models.variation_image_upload_path)),
                ('caption', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255, verbose_name='CTA')),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_selected', models.BooleanField(default=False)),
                ('generation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='creative_generation.generationrequest')),
            ],
            options={
                'ordering': ['variation_number'],
                'unique_together': {('generation_request', 'variation_number')},
            },
        ),
    ]
