# Generated by Django 5.0.6 on 2026-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrequest',
            name='creative_type',
            field=models.CharField(choices=[('instagram_post', 'Instagram Post'), ('facebook_post', 'Facebook Post'), ('linkedin_post', 'LinkedIn Post'), ('carousel', 'Carousel'), ('story', 'Story'), ('promotional_creative', 'Promotional Creative'), ('festival_creative', 'Festival Creative'), ('product_creative', 'Product Creative'), ('educational_creative', 'Educational Creative'), ('event_creative', 'Event Creative'), ('announcement_creative', 'Announcement Creative'), ('testimonial_creative', 'Testimonial Creative')], max_length=30),
        ),
    ]
