# Generated by Django 5.0.6 on 2026-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_generation', '0002_alter_generationrequest_creative_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('general', 'General / Multi-platform')], default='general', help_text='Which platform this creative is being made for - independent of creative_type (a Festival Creative can be for Instagram, Facebook, or LinkedIn).', max_length=15),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='creative_type',
            field=models.CharField(choices=[('instagram_post', 'Instagram Post'), ('facebook_post', 'Facebook Post'), ('linkedin_post', 'LinkedIn Post'), ('post', 'Post'), ('carousel', 'Carousel'), ('story', 'Story'), ('promotional_creative', 'Promotional Creative'), ('festival_creative', 'Festival Creative'), ('product_creative', 'Product Creative'), ('educational_creative', 'Educational Creative'), ('event_creative', 'Event Creative'), ('announcement_creative', 'Announcement Creative'), ('testimonial_creative', 'Testimonial Creative')], max_length=30),
        ),
    ]
