# Generated by Django 5.0.6 on 2026-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_generation', '0003_generationrequest_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='variation_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many variations to generate (1-3) - lower it while testing to save AI credits.'),
        ),
    ]
