# Generated by Django 5.0.6 on 2026-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_generation', '0004_generationrequest_variation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='include_text_overlay',
            field=models.BooleanField(default=False, help_text='Composite an AI-written headline banner and CTA button onto the image itself. Off by default - a plain clean photo is usually the better result; the headline/caption/CTA copy is still generated and stored either way, just not baked into the image pixels unless this is explicitly turned on.'),
        ),
    ]
