# Generated by Django 5.0.6 on 2026-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_generation', '0005_generationrequest_include_text_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationvariation',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small kicker/label shown above the headline in the composited layout, e.g. "THE" or a category label.', max_length=60),
        ),
    ]
