# Generated by Django 5.0.6 on 2026-08-25 12:53

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='page_permissions',
            field=models.JSONField(blank=True, default=apps.companies.models._all_pages, help_text='List of Page keys this client can access, e.g. ["dashboard", "brand"].'),
        ),
    ]
