# Generated by Django 5.0.6 on 2026-08-25 13:20

from django.db import migrations


def add_ai_strategy_page(apps, schema_editor):
    """AI Strategy is a newly-added client-controllable page - no one could have
    consciously restricted it before now, so every existing client keeps seeing it by
    default (an admin can uncheck it afterward via Access Control), matching how
    page_permissions itself defaulted to "everything" when it was first introduced.
    """
    ClientProfile = apps.get_model('companies', 'ClientProfile')
    for profile in ClientProfile.objects.all():
        pages = profile.page_permissions or []
        if 'ai_strategy' not in pages:
            profile.page_permissions = [*pages, 'ai_strategy']
            profile.save(update_fields=['page_permissions'])


def remove_ai_strategy_page(apps, schema_editor):
    ClientProfile = apps.get_model('companies', 'ClientProfile')
    for profile in ClientProfile.objects.all():
        pages = profile.page_permissions or []
        if 'ai_strategy' in pages:
            profile.page_permissions = [p for p in pages if p != 'ai_strategy']
            profile.save(update_fields=['page_permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_clientprofile_page_permissions'),
    ]

    operations = [
        migrations.RunPython(add_ai_strategy_page, remove_ai_strategy_page),
    ]
