import datetime
from unittest.mock import patch

from django.test import TestCase
from django.utils import timezone

from apps.authentication.models import User
from apps.companies.models import Company
from apps.content_calendar.models import ContentCalendarItem
from apps.content_calendar.tasks import (
    _build_prompt_brief,
    _pick_creative_type,
    _pick_platform,
    _pick_video_type,
    auto_generate_due_content,
)
from apps.creative_generation.models import GenerationRequest
from apps.video_generation.models import VideoGenerationRequest


def make_item(company, **overrides):
    defaults = {
        'company': company,
        'topic': 'New arrivals',
        'content_type': 'Static Post',
        'platforms': ['instagram'],
        'scheduled_date': timezone.localdate(),
        'status': ContentCalendarItem.Status.DRAFT,
    }
    defaults.update(overrides)
    return ContentCalendarItem.objects.create(**defaults)


class AutoGenerateDueContentTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_superuser(email='admin@example.com', password='StrongPass123!')
        self.company = Company.objects.create(name='Acme Retail', created_by=self.admin)

    @patch('apps.content_calendar.tasks._enqueue_creative')
    def test_picks_up_due_draft_item_and_creates_generation_request(self, mock_enqueue):
        item = make_item(self.company)

        auto_generate_due_content()

        item.refresh_from_db()
        self.assertEqual(item.status, ContentCalendarItem.Status.GENERATING)
        request = GenerationRequest.objects.get(content_calendar_item=item)
        self.assertEqual(request.company, self.company)
        mock_enqueue.assert_called_once_with(request)

    @patch('apps.content_calendar.tasks._enqueue_creative')
    def test_picks_up_overdue_scheduled_item(self, mock_enqueue):
        item = make_item(
            self.company, status=ContentCalendarItem.Status.SCHEDULED,
            scheduled_date=timezone.localdate() - datetime.timedelta(days=2),
        )

        auto_generate_due_content()

        item.refresh_from_db()
        self.assertEqual(item.status, ContentCalendarItem.Status.GENERATING)
        mock_enqueue.assert_called_once()

    @patch('apps.content_calendar.tasks._enqueue_creative')
    def test_ignores_future_item(self, mock_enqueue):
        item = make_item(self.company, scheduled_date=timezone.localdate() + datetime.timedelta(days=1))

        auto_generate_due_content()

        item.refresh_from_db()
        self.assertEqual(item.status, ContentCalendarItem.Status.DRAFT)
        mock_enqueue.assert_not_called()
        self.assertFalse(GenerationRequest.objects.exists())

    @patch('apps.content_calendar.tasks._enqueue_creative')
    def test_ignores_item_already_past_draft_or_scheduled(self, mock_enqueue):
        make_item(self.company, status=ContentCalendarItem.Status.GENERATING)
        make_item(self.company, status=ContentCalendarItem.Status.GENERATED)
        make_item(self.company, status=ContentCalendarItem.Status.APPROVED)

        auto_generate_due_content()

        mock_enqueue.assert_not_called()
        self.assertFalse(GenerationRequest.objects.exists())

    @patch('apps.content_calendar.tasks._enqueue_creative')
    def test_ignores_item_scheduled_later_today(self, mock_enqueue):
        later = (timezone.localtime() + datetime.timedelta(hours=1)).time()
        item = make_item(self.company, scheduled_time=later)

        auto_generate_due_content()

        item.refresh_from_db()
        self.assertEqual(item.status, ContentCalendarItem.Status.DRAFT)
        mock_enqueue.assert_not_called()

    @patch('apps.content_calendar.tasks._enqueue_creative')
    def test_picks_up_item_scheduled_earlier_today(self, mock_enqueue):
        earlier = (timezone.localtime() - datetime.timedelta(hours=1)).time()
        item = make_item(self.company, scheduled_time=earlier)

        auto_generate_due_content()

        item.refresh_from_db()
        self.assertEqual(item.status, ContentCalendarItem.Status.GENERATING)
        mock_enqueue.assert_called_once()

    @patch('apps.content_calendar.tasks._enqueue_creative')
    def test_picks_up_item_with_no_scheduled_time_regardless_of_clock(self, mock_enqueue):
        item = make_item(self.company, scheduled_time=None)

        auto_generate_due_content()

        item.refresh_from_db()
        self.assertEqual(item.status, ContentCalendarItem.Status.GENERATING)
        mock_enqueue.assert_called_once()

    @patch('apps.content_calendar.tasks._enqueue_video')
    def test_video_keyword_content_type_creates_video_request_not_image(self, mock_enqueue):
        item = make_item(self.company, content_type='Instagram Reel')

        auto_generate_due_content()

        item.refresh_from_db()
        self.assertEqual(item.status, ContentCalendarItem.Status.GENERATING)
        request = VideoGenerationRequest.objects.get(content_calendar_item=item)
        mock_enqueue.assert_called_once_with(request)
        self.assertFalse(GenerationRequest.objects.exists())


class CreativeTypeMappingTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_superuser(email='admin2@example.com', password='StrongPass123!')
        self.company = Company.objects.create(name='Beta Co', created_by=self.admin)

    def test_keyword_match_wins_over_platform_fallback(self):
        item = make_item(self.company, content_type='Festival Creative', platforms=['facebook'])
        self.assertEqual(_pick_creative_type(item), GenerationRequest.CreativeType.FESTIVAL_CREATIVE)

    def test_falls_back_to_generic_post_with_no_keyword_match(self):
        item = make_item(self.company, content_type='Static Post', platforms=['linkedin'])
        self.assertEqual(_pick_creative_type(item), GenerationRequest.CreativeType.POST)

    def test_pick_platform_prefers_linkedin(self):
        item = make_item(self.company, platforms=['instagram', 'linkedin'])
        self.assertEqual(_pick_platform(item), GenerationRequest.Platform.LINKEDIN)

    def test_pick_platform_prefers_facebook_over_instagram(self):
        item = make_item(self.company, platforms=['instagram', 'facebook'])
        self.assertEqual(_pick_platform(item), GenerationRequest.Platform.FACEBOOK)

    def test_pick_platform_instagram(self):
        item = make_item(self.company, platforms=['instagram'])
        self.assertEqual(_pick_platform(item), GenerationRequest.Platform.INSTAGRAM)

    def test_pick_platform_falls_back_to_general(self):
        item = make_item(self.company, platforms=[])
        self.assertEqual(_pick_platform(item), GenerationRequest.Platform.GENERAL)

    def test_educational_keyword_match(self):
        item = make_item(self.company, content_type='Educational Post', platforms=['instagram'])
        self.assertEqual(_pick_creative_type(item), GenerationRequest.CreativeType.EDUCATIONAL_CREATIVE)

    def test_event_keyword_match(self):
        item = make_item(self.company, content_type='Event Announcement', platforms=['instagram'])
        self.assertEqual(_pick_creative_type(item), GenerationRequest.CreativeType.EVENT_CREATIVE)

    def test_testimonial_keyword_match(self):
        item = make_item(self.company, content_type='Testimonial Post', platforms=['instagram'])
        self.assertEqual(_pick_creative_type(item), GenerationRequest.CreativeType.TESTIMONIAL_CREATIVE)

    def test_video_type_keyword_match(self):
        item = make_item(self.company, content_type='Short educational video', platforms=['instagram'])
        self.assertEqual(_pick_video_type(item), VideoGenerationRequest.VideoType.SHORT_VIDEO)

    def test_video_type_platform_fallback(self):
        item = make_item(self.company, content_type='Reel', platforms=['facebook'])
        self.assertEqual(_pick_video_type(item), VideoGenerationRequest.VideoType.FACEBOOK_REEL)


class PromptBriefTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_superuser(email='admin3@example.com', password='StrongPass123!')
        self.company = Company.objects.create(name='Gamma Co', created_by=self.admin)

    def test_includes_topic_requirements_and_cta(self):
        item = make_item(
            self.company, topic='Diwali sale', creative_requirements='Festive gold tones',
            caption_requirements='Mention 20% off', cta='Shop now',
        )
        brief = _build_prompt_brief(item)
        self.assertIn('Diwali sale', brief)
        self.assertIn('Festive gold tones', brief)
        self.assertIn('Mention 20% off', brief)
        self.assertIn('Shop now', brief)
