# Generated by Django 5.0.6 on 2026-08-17 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('promotional', 'Promotional'), ('educational', 'Educational'), ('festival', 'Festival'), ('product', 'Product'), ('announcement', 'Announcement'), ('testimonial', 'Testimonial')], max_length=20)),
                ('content_type', models.CharField(choices=[('single_image', 'Single Image'), ('carousel', 'Carousel'), ('grid', 'Grid'), ('story', 'Story'), ('reel', 'Reel'), ('short_video', 'Short Video')], max_length=20)),
                ('platforms', models.JSONField(default=list, help_text='List of platform codes, e.g. ["instagram", "facebook"].')),
                ('objective', models.CharField(blank=True, max_length=255)),
                ('campaign', models.CharField(blank=True, max_length=255)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('caption_requirements', models.TextField(blank=True)),
                ('creative_requirements', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=255, verbose_name='CTA')),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('generating', 'Generating'), ('generated', 'Generated'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('excel_import', 'Excel Import')], default='manual', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_calendar_items', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_calendar_items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time', '-created_at'],
            },
        ),
    ]
