# Generated by Django 5.0.6 on 2026-08-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcalendaritem',
            name='source_notes',
            field=models.CharField(blank=True, help_text='Reference / inspiration source, if any.', max_length=500),
        ),
        migrations.AddField(
            model_name='contentcalendaritem',
            name='weekly_theme',
            field=models.CharField(blank=True, help_text='e.g. "Leadership", "Community".', max_length=255),
        ),
        migrations.AlterField(
            model_name='contentcalendaritem',
            name='caption_requirements',
            field=models.TextField(blank=True, help_text='Caption / content idea copy.'),
        ),
        migrations.AlterField(
            model_name='contentcalendaritem',
            name='category',
            field=models.CharField(blank=True, help_text='Coarse internal classification, optional.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentcalendaritem',
            name='content_type',
            field=models.CharField(help_text='Format, e.g. "Static Post", "Reel", "Carousel".', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentcalendaritem',
            name='creative_requirements',
            field=models.TextField(blank=True, help_text='Visual brief.'),
        ),
        migrations.AlterField(
            model_name='contentcalendaritem',
            name='topic',
            field=models.CharField(help_text='Topical / content idea, e.g. "National Doctor\'s Day".', max_length=255),
        ),
    ]
