# Generated by Django 5.0.6 on 2026-08-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_calendar', '0002_contentcalendaritem_source_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcalendaritem',
            name='client_feedback',
            field=models.TextField(blank=True, help_text="Client's rejection feedback / change request."),
        ),
        migrations.AddField(
            model_name='contentcalendaritem',
            name='regeneration_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many times this item has been auto-regenerated after a rejection (max 1).'),
        ),
    ]
