# Generated by Django 5.0.6 on 2026-08-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_calendar', '0003_contentcalendaritem_client_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcalendaritem',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('excel_import', 'Excel Import'), ('ad_hoc', 'Ad Hoc Generation')], default='manual', max_length=20),
        ),
    ]
