# Generated by Django 5.0.6 on 2026-10-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        ('content_calendar', '0004_alter_contentcalendaritem_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generated', 'Submitted for review'), ('regenerated', 'Regenerated & resubmitted'), ('generation_failed', 'Generation failed'), ('variation_selected', 'Variation selected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('regeneration_requested', 'Regeneration requested'), ('reminder_sent', 'Approval reminder sent'), ('scheduled', 'Scheduled for publishing'), ('published', 'Published'), ('publish_failed', 'Publishing failed')], max_length=30)),
                ('actor_role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('system', 'System')], default='system', max_length=10)),
                ('feedback', models.TextField(blank=True, help_text='Rejection reason / change request / note.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_review_events', to='companies.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='content_calendar.contentcalendaritem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'action', '-created_at'], name='content_cal_company_1b8e35_idx'), models.Index(fields=['item', '-created_at'], name='content_cal_item_id_43536d_idx')],
            },
        ),
    ]
