# Generated by Django 5.0.6 on 2026-10-01 21:50

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_backfill_ai_strategy_page_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly report'), ('content', 'Content report'), ('publishing', 'Publishing report'), ('engagement', 'Engagement report'), ('growth', 'Growth report'), ('company_overview', 'Company report'), ('client_overview', 'Client report'), ('ai_usage', 'AI usage report'), ('approval', 'Approval report'), ('publishing_overview', 'Publishing report (all companies)'), ('subscription', 'Subscription report')], max_length=25)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.reports.models.report_upload_path)),
                ('xlsx_file', models.FileField(blank=True, null=True, upload_to=apps.reports.models.report_upload_path)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to=apps.reports.models.report_upload_path)),
                ('is_automated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'report_type', 'period_start'], name='reports_rep_company_ef3fe0_idx'), models.Index(fields=['status'], name='reports_rep_status_c732ef_idx')],
            },
        ),
    ]
