# Generated by Django 5.0.6 on 2026-09-23 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Groups versions of the same template together.', max_length=80)),
                ('category', models.CharField(choices=[('image', 'Image Prompt'), ('caption', 'Caption Prompt'), ('video', 'Video Prompt'), ('hashtag', 'Hashtag Prompt'), ('campaign', 'Campaign Prompt')], max_length=20)),
                ('platform', models.CharField(blank=True, help_text='Optional: instagram / facebook / linkedin / general. Blank = applies to every platform.', max_length=20)),
                ('creative_type', models.CharField(blank=True, help_text='Optional: e.g. festival_creative, product_creative. Blank = applies to every creative type.', max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='Extra guidance appended into the AI prompt for matching generations.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', '-version'], name='prompt_temp_slug_ef29b9_idx'), models.Index(fields=['category', 'is_active'], name='prompt_temp_categor_194255_idx')],
            },
        ),
    ]
