# Generated by Django 5.0.6 on 2026-08-19 11:44

import apps.brand.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('logo_upload', 'Logo Upload'), ('reference_image', 'Reference Image'), ('product_image', 'Product Image'), ('document', 'Document'), ('marketing_material', 'Marketing Material')], max_length=20)),
                ('file', models.FileField(upload_to=apps.brand.models.brand_asset_upload_path)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_assets_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.brand.models.brand_identity_upload_path)),
                ('secondary_logo', models.ImageField(blank=True, null=True, upload_to=apps.brand.models.brand_identity_upload_path)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.brand.models.brand_identity_upload_path)),
                ('brand_colors', models.JSONField(blank=True, default=list, help_text='List of {"name": "Primary", "hex": "#AA3BFF"} objects.')),
                ('fonts', models.JSONField(blank=True, default=list, help_text='List of {"name": "Poppins", "usage": "Headings"} objects.')),
                ('typography_notes', models.TextField(blank=True, help_text='General typography guidance.')),
                ('brand_voice', models.TextField(blank=True)),
                ('tone', models.TextField(blank=True)),
                ('writing_style', models.TextField(blank=True)),
                ('visual_style', models.TextField(blank=True)),
                ('dos', models.JSONField(blank=True, default=list, help_text='List of things to do.')),
                ('donts', models.JSONField(blank=True, default=list, help_text='List of things to avoid.')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Preferred keywords/phrases.')),
                ('restricted_words', models.JSONField(blank=True, default=list, help_text='Words/phrases to avoid.')),
                ('customer_personas', models.JSONField(blank=True, default=list, help_text='List of {"name": ..., "summary": ...} persona objects.')),
                ('offers', models.JSONField(blank=True, default=list, help_text='List of current offers/promotions.')),
                ('campaign_information', models.TextField(blank=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='companies.company')),
            ],
            options={
                'verbose_name': 'Brand Profile',
            },
        ),
    ]
